services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [qdms]

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks: [qdms]

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API (içeride kalsın; internetten açmayın)
      - "9001:9001"   # MinIO Console (sadece LAN)
    volumes:
      - miniodata:/data
    networks: [qdms]

  # İlk açılışta bucket/versiyon/lock politikalarını ayarlar
  minio-setup:
    image: minio/mc:latest
    depends_on: [minio]
    networks: [qdms]
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb --ignore-existing --with-lock local/${MINIO_BUCKET_MAIN} &&
      mc mb --ignore-existing --with-lock local/${MINIO_BUCKET_ARCHIVE} &&
      mc mb --ignore-existing local/${MINIO_BUCKET_PREVIEWS} &&
      mc version enable local/${MINIO_BUCKET_MAIN} &&
      mc version enable local/${MINIO_BUCKET_ARCHIVE} &&
      mc ilm add local/${MINIO_BUCKET_ARCHIVE} --expiry-days 3650 --noncurrent-expiry-days 3650 &&
      echo 'MinIO buckets ready.';
      "
    restart: "no"

  onlyoffice:
    image: onlyoffice/documentserver:latest
    restart: unless-stopped
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: ${ONLYOFFICE_JWT_SECRET}
      JWT_HEADER: ${ONLYOFFICE_JWT_HEADER}
    # Eğer büyük dosyalar/çok kullanıcı planı varsa CPU/RAM artırın
    networks: [qdms]

  portal:
    build: ./portal
    restart: unless-stopped
    environment:
      FLASK_ENV: production
      SECRET_KEY: ${PORTAL_SECRET_KEY}
      DEBUG: ${PORTAL_DEBUG}
      BIND: ${PORTAL_BIND}
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/0
      ONLYOFFICE_INTERNAL_URL: ${ONLYOFFICE_INTERNAL_URL}
      ONLYOFFICE_PUBLIC_URL: ${ONLYOFFICE_PUBLIC_URL}
      ONLYOFFICE_JWT_SECRET: ${ONLYOFFICE_JWT_SECRET}
      ONLYOFFICE_JWT_HEADER: ${ONLYOFFICE_JWT_HEADER}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET_MAIN: ${S3_BUCKET_MAIN}
      S3_BUCKET_ARCHIVE: ${S3_BUCKET_ARCHIVE}
      S3_BUCKET_PREVIEWS: ${S3_BUCKET_PREVIEWS}
      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE}
      LDAP_ENABLED: ${LDAP_ENABLED}
      LDAP_URL: ${LDAP_URL}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_USER: ${LDAP_USER}
      LDAP_PASSWORD: ${LDAP_PASSWORD}
      LDAP_SEARCH_FILTER: ${LDAP_SEARCH_FILTER}
      PORTAL_JWT_SECRET: ${PORTAL_JWT_SECRET}
    depends_on:
      - postgres
      - redis
      - minio
      - minio-setup
      - onlyoffice
    networks: [qdms]

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      - portal
      - onlyoffice
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_cache:/var/cache/nginx
      # SSL sertifikası kullanacaksanız aşağıyı açın ve dosyaları koyun
      # - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "8090:80"
      # - "443:443"
    networks: [qdms]

volumes:
  pgdata:
  redisdata:
  miniodata:
  nginx_cache:

networks:
  qdms:
    driver: bridge
